stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw/train.csv
    - src/preprocess.py
    outs:
    - data/processed/train.csv
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/processed/train.csv
    - models/model.pkl
    - src/evaluate.py
    metrics:
    - metrics.json:
        cache: false
